version: '3.8'

services:
  app:
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres: